services:
  ruby: 
    build: 
      context: .
      target: base
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle

  api1: &api
    build: 
      context: .
      target: base
    container_name: api1
    environment:
      - DATABASE_HOST=postgres
      - RUBY_YJIT_ENABLE=1
      - ASYNC=1
    command: ruby server.rb
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '100MB'

  api2: 
    <<: *api
    container_name: api2

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c max_connections=30
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '300MB'

  nginx:
    image: nginx 
    container_name: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9999:9999
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '50MB'

volumes:
  rubygems:
